language: java

jdk:
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

services:
#  - docker
  - postgresql

before_script:
  - psql -c 'create database testDB;' -U postgres

script:
  - ./gradlew clean test
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME

notifications:
  email:
    on_success: never
    on_failure: always
