server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://192.168.99.100:5432/testdb

swagger:
  title: REST-Сервис
  version: 0.0.1
  description: Описание сервиса в разработке
  contact:
    mail: steklopod@gmail.com
    url: http://doppo.io
    name: Дмитрий Колтович
